openapi: 3.0.0
info:
  version: 1.0.0
  title: Realmeet
#servers:
#  - url: '127.0.0.1:8080/v1'
paths:
  /rooms/{id}:
    get:
      summary: 'Retorna uma room pelo id'
      operationId: getRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          required : true
          description: 'Id da room'
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: 'Not found'
    delete:
      summary: 'Inativa uma room pelo id'
      operationId: deleteRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          required: true
          description: 'Id da room'
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        204:
          description: 'Deletado'
        404:
          description: 'Not found'
    put:
      summary: 'Atualiza uma room'
      operationId: updateRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          required: true
          description: Id da room
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDTO'
        required: true
      responses:
        204:
          description: 'Update success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: 'Not found'
        422:
          description: Unprocessable entity
          $ref: '#/components/responses/UnprocessableEntity'
  /rooms:
    post:
      summary: 'Cria uma room'
      operationId: createRoom
      tags:
        - room
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        422:
          description: Unprocessable entity
          $ref: '#/components/responses/UnprocessableEntity'
  /allocations:
    post:
      summary: 'Cria uma alocação'
      operationId: createAllocation
      tags:
        - allocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAllocationDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllocationDTO'
        404:
          description: 'Not found'
        422:
          description: Unprocessable entity
          $ref: '#/components/responses/UnprocessableEntity'
  /allocations/{id}:
    delete:
      summary: 'Deletes an allocation by id'
      operationId: deleteAllocation
      tags:
        - allocation
      parameters:
        - name: id
          in: path
          required: true
          description: 'Id of the allocation'
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        204:
          description: 'Deleted Successfully'
        404:
          description: 'Not found'
        422:
          description: Unprocessable entity
          $ref: '#/components/responses/UnprocessableEntity'
components:
  schemas:
    UpdateRoomDTO:
      type: object
      properties:
        name:
          type: string
        seats:
          type: integer
          minimum: 1
    CreateRoomDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpdateRoomDTO'
    RoomDTO:
      type: object
      allOf:
        - $ref : '#/components/schemas/CreateRoomDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              minimum: 1
    CreateAllocationDTO:
      type: object
      properties:
        subject:
          type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time
        roomId:
          type: integer
          format: int64
          minimum: 1
        employeeName:
          type: string
        employeeEmail:
          type: string
          format: email
    AllocationDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateAllocationDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              minimum: 1
    ResponseError:
      type: object
      required:
        - field
        - errorCode
      properties:
        field:
          type: string
        errorCode:
          type: string
  responses:
    UnprocessableEntity:
      description: The server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref : '#/components/schemas/ResponseError'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []