openapi: 3.0.0
info:
  version: 1.0.0
  title: Realmeet
servers:
  - url: '127.0.0.1:8080/v1'
paths:
  /rooms/{id}:
    get:
      summary: 'Retorna uma room pelo id'
      operationId: getRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          required : true
          description: 'Id da room'
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /rooms:
    post:
      summary: 'Cria uma room'
      operationId: createRoom
      tags:
        - room
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDTO'
        required: true

      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        422:
          description: Unprocessable entity
          $ref: '#/components/responses/UnprocessableEntity'
components:
  schemas:
    CreateRoomDTO:
      type: object
      properties:
        name:
          type: string
        seats:
          type: integer
          minimum: 0
    RoomDTO:
      type: object
      allOf:
        - $ref : '#/components/schemas/CreateRoomDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
    ResponseError:
      type: object
      required:
        - field
        - errorCode
      properties:
        field:
          type: string
        errorCode:
          type: string
  responses:
    UnprocessableEntity:
      description: The server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref : '#/components/schemas/ResponseError'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
